title: SQL for Data Scientists in 100 Queries
url: https://gvwilson.github.io/sql-tutorial/
repo: https://github.com/gvwilson/sql-tutorial
release: https://github.com/gvwilson/sql-tutorial/raw/main/sql-tutorial.zip
plausible: gvwilson.github.io/sql-tutorial
author:
  name: Greg Wilson
  url: https://third-bit.com
  email: gvwilson@third-bit.com
